### ISSUE TITLE
[Bug]: transactions filter

### ISSUE THREAD

**Issue by bogdanIuga** [multiversx/mx-api-service#749]
### Contact Details

iugabogdan13@gmail.com

### Description

status filter not working

### Steps to reproduce

Status filter does not work. I set it to get only success transactions, but I also get pending transactions

1. go to api.elrond.com
2. go to GET /transactions
3. set status filter to success
4. execute
5. look in the response until a pending transaction is returned

Please check if the same issue happens to GET transactions/count

![image](https://user-images.githubusercontent.com/26706013/182040222-dbef13a8-7f2d-4421-9c17-2be12cdb41af.png)

### On which network is the bug manifesting itself?

Mainnet

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by tanghel** [comment]
Hello!

Indeed, this is confusing.

The reasoning behind this is that actually pending transactions are actually transactions with status `success`, but are still awaiting results from cross-shard smart contracts.

If you quickly look up the transaction on index.elrond.com or on gateway.elrond.com, you will see it actually has the status `success`. We are actually setting the status on pending artificially on api.elrond.com level, so that we know that the given transaction still has something to execute.

Will open some discussions internally so that we might get the `cross-shard-scr-pending` status directly in the indexer, then we can filter by success as expected.

**Comment by bogdanIuga** [comment]
the pending status from the API turns into a failed status... just caught this case.

So the status filter is useless for the APIs

Any updates?

**Comment by tanghel** [comment]
a transaction has status pending while it is being processed, then the status changes to "success", "failed", etc.

the indexer team is already working on providing the real transaction status in the elasticsearch, thus solving the "success as pending" transaction issue.

we would really appreciate to receive constructive criticism and focus on the issues at hand.

**Comment by bogdanIuga** [comment]
I'm sorry for that, it was a long and very frustrating day...

We'll refactor to get the transactions with a delay of ~1 minute using the timestamp filter and see how it goes.

**Comment by miiu96** [comment]
Can we close this issue? @bogdanIuga
