### ISSUE TITLE
Allowing herotags fetch for Smart Contracts

### ISSUE THREAD

**Issue by aledefra** [multiversx/mx-api-service#930]
Hi there!
Is there any specific reason for not allowing the fetch of herotags for Smart Contract addresses?
I see this is specified here:
https://github.com/multiversx/mx-api-service/blob/286c43d3c8f1632d5cc29fe90a51e771f55e39d6/src/endpoints/accounts/account.service.ts#L112
But I think getting herotags for SCs would be very useful, so owners who set it can have a name shown in explorer (just as it is in inspire.art). Waiting for branding approvals is not always the best option, as it requires a lot of patience and lots of smart contracts (and tokens) are not approved for branding.

**Comment by tanghel** [comment]
fixed in https://github.com/multiversx/mx-api-service/pull/937

**Comment by tanghel** [comment]
backtracked on this one, since:
- herotags are fetched from maiar id, which should be impossible for a smart contract to register itself on maiar id
- there is already the possibility to attach human-readable names to smart contracts with the help of assets

**Comment by tanghel** [comment]
if accounts or tokens are not approved for branding means that maybe some legitimate issue is raised.
because of the above issue, we recommend going through our standard process of branding accounts using assets.
we have a developer telegram channel, recently also opened a discord, so enough ways to interact with us.
Thank you for your understanding
